"""empty message

Revision ID: 2a38e35c07bb
Revises: cba787d1705f
Create Date: 2022-12-10 02:06:13.460760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a38e35c07bb'
down_revision = 'cba787d1705f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('_password',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=100000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('_password',
               existing_type=sa.String(length=100000),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)

    # ### end Alembic commands ###
