"""Initial migration.

Revision ID: 6203ae99105e
Revises: 
Create Date: 2022-12-07 20:29:44.667595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6203ae99105e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocked_contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blocker_id', postgresql.UUID(as_uuid=True), nullable=True))
        batch_op.add_column(sa.Column('blockee_id', postgresql.UUID(as_uuid=True), nullable=True))
        batch_op.drop_constraint('blocked_contact_blocker_blockee_key', type_='unique')
        batch_op.create_unique_constraint(None, ['blocker_id', 'blockee_id'])
        batch_op.drop_constraint('blocked_contact_blockee_fkey', type_='foreignkey')
        batch_op.drop_constraint('blocked_contact_blocker_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['blocker_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['blockee_id'], ['id'])
        batch_op.drop_column('blockee')
        batch_op.drop_column('blocker')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocked_contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blocker', postgresql.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('blockee', postgresql.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('blocked_contact_blocker_fkey', 'user', ['blocker'], ['id'])
        batch_op.create_foreign_key('blocked_contact_blockee_fkey', 'user', ['blockee'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('blocked_contact_blocker_blockee_key', ['blocker', 'blockee'])
        batch_op.drop_column('blockee_id')
        batch_op.drop_column('blocker_id')

    # ### end Alembic commands ###
